<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette;
use Tracy\Debugger;


/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->template->isAutorizate = $this->getUser()->isLoggedIn();
        $this->template->userRole = $this->getUser()->roles[0];
        Debugger::barDump($this->getUser());
    }
}
